---
- name: "Install OpenHPC release package"
  package:
    name: http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm
    disable_gpg_check: true
    state: present

- name: "Install base prereqs"
  package:
    name:
      - buildah
      - jq
    state: present

# FIXME: some of these are only needed on the head node
- name: "Install base python packages"
  pip:
    name:
      - jmespath
      - kubernetes
      - netaddr
      - selinux

- name: "Disable firewall"
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: "Disable selinux"
  selinux:
    state: "disabled"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add slurm alias to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars["head"]["netconfig"]["ipv4_address"] }} slurm
    marker: "# {mark} ANSIBLE MANAGED BLOCK slurm"

- name: Add cluster nodes to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars[item]["netconfig"]["ipv4_address"] }} {{ item }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  loop: "{{ groups['all'] }}"
