---
- name: "Install OpenHPC release package"
  package:
    name: http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm
    disable_gpg_check: true
    state: present

- name: "Install base prereqs"
  package:
    name:
      - ansible
      - buildah
      - jq
      - python3-libselinux
      - python3-openshift
    state: present

- name: "Disable firewall"
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: "Disable selinux"
  selinux:
    state: "disabled"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add cluster nodes to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.100.2 slurm
      192.168.100.101	node01
      192.168.100.102	node02
      192.168.100.103	node03
      192.168.100.104	node04
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
