---
## Build container images
- name: "Get container list"
  command: "buildah images --json"
  register: buildahoutput
  changed_when: False

- name: "Create the slurmctld container"
  block:
  - name: "Build the slurmctld container if it doesn't exist"
    ansible.builtin.command: "buildah build-using-dockerfile -t slurmctld /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/slurmcontainer/"
  - name: "Push the slurmctld container into the local registry"
    ansible.builtin.command: "buildah push --tls-verify=false localhost/slurmctld 192.168.100.2:5000/slurmctld"
  when: "not buildahoutput.stdout | from_json | json_query('contains([].names[], `localhost/slurmctld:latest`)')"

- name: "Create the munge container"
  block:
  - name: "Build the munge container if it doesn't exist"
    ansible.builtin.command: "buildah build-using-dockerfile -t munge /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/mungecontainer/"
  - name: "Push the munge container into the local registry"
    ansible.builtin.command: "buildah push --tls-verify=false localhost/munge 192.168.100.2:5000/munge"
  when: "not buildahoutput.stdout | from_json | json_query('contains([].names[], `localhost/munge:latest`)')"

## Prepare local install
- name: "Install slurm and munge locally"
  package:
    name:
      - munge
      - slurm-ohpc
    state: present

- name: "Create the slurm.conf configmap"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition: "{{ lookup('template', 'slurm-conf-configmap.yaml.j2') | from_yaml }}"
    state: present

- name: "Create a munge key"
  ansible.builtin.shell: "dd if=/dev/urandom bs=1 count=1024 > {{ role_path }}/files/munge.key"
  args:
    creates: "{{ role_path }}/files/munge.key"

- name: "Set permissions on the munge key in the repository"
  file:
    path: "{{ role_path }}/files/munge.key"
    mode: 0400

- name: "Create the munge key secret"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition: "{{ lookup('template', 'munge-conf-secret.yaml.j2') | from_yaml }}"
    state: present

- name: "Install munge locally"
  ansible.builtin.copy:
    src: "munge.key"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: 0400

- name: "Enable and start munge"
  ansible.builtin.service:
    name: munge
    enabled: yes
    state: started

- name: "Create the slurmctld deployment object"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "/home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/slurmctld-deployment.yaml"
    state: present

- name: "Create the slurmctld service object"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "/home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/slurmctld-service.yaml"
    state: present

