---
## Prepare local install
- name: "Install slurm and munge locally"
  package:
    name:
      - munge
      - slurm-ohpc
    state: present

- name: "Create the /etc/slurm directory"
  file:
    path: /etc/slurm
    state: directory
    mode: '0755'

- name: "Install slurm.conf locally"
  template:
    src: "slurm.conf.j2"
    dest: "/etc/slurm/slurm.conf"
    owner: root
    group: root
    mode: 0644

- name: "Create a munge key"
  ansible.builtin.shell: "dd if=/dev/urandom bs=1 count=1024 > {{ role_path }}/files/munge.key"
  args:
    creates: "{{ role_path }}/files/munge.key"

- name: "Set permissions on the munge key in the repository"
  file:
    path: "{{ role_path }}/files/munge.key"
    mode: 0400

# FIXME: this should have a handler to restart munge if it changes
- name: "Install munge key"
  ansible.builtin.copy:
    src: "munge.key"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: 0400

- name: "Enable and start munge"
  ansible.builtin.service:
    name: munge
    enabled: yes
    state: started

- name: Include Server Tasks
  include_tasks: server.yaml
  when: enable_slurm_server is true

- name: Include Client Tasks
  include_tasks: client.yaml
  when: enable_slurm_client is true