---
## Build container images
- name: "Get container list"
  command: "buildah images --json"
  register: buildahoutput
  changed_when: False

- name: "Create the slurmctld container"
  block:
  - name: "Build the slurmctld container"
    ansible.builtin.command: "buildah build-using-dockerfile -t slurmctld {{ role_path }}/containers/slurmcontainer/"
  - name: "Push the slurmctld container into the local registry"
    ansible.builtin.command: "buildah push --tls-verify=false localhost/slurmctld {{ hostvars['head']['netconfig']['ipv4_address'] }}:5000/slurmctld"
  when:
    - not buildahoutput.stdout | from_json | json_query('contains([].names[], `localhost/slurmctld:latest`)')

- name: "Create the munge container"
  block:
  - name: "Build the munge container"
    ansible.builtin.command: "buildah build-using-dockerfile -t munge {{ role_path }}/containers/mungecontainer/"
  - name: "Push the munge container into the local registry"
    ansible.builtin.command: "buildah push --tls-verify=false localhost/munge {{ hostvars['head']['netconfig']['ipv4_address'] }}:5000/munge"
  when:
    - not buildahoutput.stdout | from_json | json_query('contains([].names[], `localhost/munge:latest`)')

- name: "Create the slurm.conf configmap"
  kubernetes.core.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition: "{{ lookup('template', 'slurm-conf-configmap.yaml.j2') | from_yaml }}"
    state: present

- name: "Create the munge key secret"
  kubernetes.core.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition: "{{ lookup('template', 'munge-conf-secret.yaml.j2') | from_yaml }}"
    state: present

- name: "Create the slurmctld deployment object"
  kubernetes.core.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition: "{{ lookup('template', 'defs/slurmctld-deployment.yaml.j2') | from_yaml }}"
    state: present

- name: "Create the slurmctld service object"
  kubernetes.core.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition: "{{ lookup('template', 'defs/slurmctld-service.yaml.j2') | from_yaml }}"
    state: present
