---
- hosts: head
  roles:
  - { role: base, tags: ['base'] }
  - { role: chrony, tags: ['chrony'] }
  - { role: sssd, tags: ['sssd'] }
  - { role: k3s, tags: ['k3s'] }
  - { role: container_registry, tags: ['container_registry'] }
  - { role: slurm_server, tags: ['slurm_server'] }
