apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: default
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
  type: LoadBalancer
