---
- name: "Build the sssd container if it doesn't exist"
  ansible.builtin.command: "buildah build-using-dockerfile -t sssd /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/sssdcontainer"
  when: "not buildahoutput.stdout | from_json | json_query('contains([].names[], `localhost/sssd:latest`)')"

- name: "Push the sssd container into the local registry"
  ansible.builtin.command: "buildah push --tls-verify=false localhost/sssd 192.168.100.2:5000/sssd"
