---
- name: "Get container list"
  command: "buildah images --json"
  register: buildahoutput

- name: "Build the chrony container if it doesn't exist"
  ansible.builtin.command: "buildah build-using-dockerfile -t chrony /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/chronycontainer/"
  when: "not buildahoutput.stdout | from_json | json_query('contains([].names[], `localhost/chrony:latest`)')"

- name: "Push the chrony container into the local registry"
  ansible.builtin.command: "buildah push --tls-verify=false localhost/chrony 192.168.100.2:5000/chrony"

- name: "Create the chrony.conf configmap"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    definition: "{{ lookup('template', 'chrony-conf-configmap.yaml.j2') | from_yaml }}"
    state: present

- name: "Create the chronyd deployment object"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "/home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/chronyd-deployment.yaml"
    state: present

- name: "Create the chronyd service object"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: "/home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/chronyd-service.yaml"
    state: present
