---
- name: "Create a local path PVC"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/local-path-pvc.yaml
    state: present

- name: "Create a docker registry deployment"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/docker-registry-deployment.yaml
    state: present

- name: "Create a docker registry service"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/docker-registry-service.yaml
    state: present

- name: "Wait for registry service to start"
  shell: /usr/local/bin/kubectl get pods -l app=docker-registry -o json | jq -r '.items[].status.phase // "NotCreated"'
  register: _result
  until: _result.stdout == "Running"
  retries: 120
  delay: 5
  changed_when: false
