---
- name: "Create a local path PVC"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/local-path-pvc.yaml
    state: present

- name: "Create a docker registry deployment"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/docker-registry-deployment.yaml
    state: present

- name: "Create a docker registry service"
  community.kubernetes.k8s:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    src: /home/vagrant/vagrant-k3s-hpccluster/kubeconfig/defs/docker-registry-service.yaml
    state: present

- name: "Wait for registry service to start"
  wait_for:
    host: 192.168.100.2
    port: 5000
